### ISSUE TITLE
[FEAT] Offline mode for iseries or VE migration

### ISSUE THREAD

**Issue by dwigley** [f5devcentral/f5-journeys#59] opened 2022-05-13 19:14 UTC
**Is your feature request related to a problem? Please describe.**
Would like more choices for offline system than VELOS and rSeries.

**Describe the solution you'd like**
Currently I only see VELOS and rSeries devices as offline destinations. Would it be possible to add addtional options like VE and iSeries Hardware and then select a TMOS version?

**Describe alternatives you've considered**
Looks like it will sort of work if I don't choose an Offline Destination BIG-IP it will read the destination it seems. I haven't done any testing if it just thinks every destination is F5OS based or not.

**Additional context**
![image](https://user-images.githubusercontent.com/4759771/168374515-1862ec26-3289-42df-8b6c-b69be35428e3.png)

**Comment by rjouhann** [comment] 2022-05-13 19:24
Filed internal Jira SOLUTIONS-5766 (also same request as https://github.com/f5devcentral/f5-journeys/issues/47)

**Comment by rjouhann** [comment] 2022-05-13 19:25
I will close this request as a duplicate of #47

**Closed by rjouhann** 2022-05-13 19:25 UTC
