### ISSUE TITLE
Celery worker will not start

### ISSUE THREAD

**Issue by sobrien10** [f5devcentral/f5-journeys#33] opened 2022-02-02 14:44 UTC
I followed the install steps exactly but celery worker will not start

**To Reproduce**
Install following the steps in the readme

<img width="782" alt="Screenshot 2022-02-02 at 14 38 49" src="https://user-images.githubusercontent.com/25149692/152175047-f306308b-cea7-4d43-a7cc-78bc96d9ef89.png">

**Context**
Docker version 4.4.2 (73305)
Journeys APP 3.2.3

**Comment by jszczepanskif5** [comment] 2022-02-07 13:41
Could not reproduce the issue locally. Luckily after a call with mr OBrien the problem seems to have resolved itself - perhaps a system reboot has helped. I'm closing the issue for now.

**Closed by jszczepanskif5** 2022-02-07 13:41 UTC
Labels: bug
